### ISSUE TITLE
Calling Non-checksummed download of openssl formula file from an arbitrary URL is disabled! Use 'brew extract' or 'brew create' and 'brew tap-new' to create a formula file in a tap on GitHub instead.

### ISSUE THREAD

**Issue by nagamanojds** [tebelorg/Tump#1]
Calling Non-checksummed download of openssl formula file from an arbitrary URL is disabled! Use 'brew extract' or 'brew create' and 'brew tap-new' to create a formula file in a tap on GitHub instead.

**Comment by londerson** [comment]
1- Download the file:
`wget https://github.com/tebelorg/Tump/releases/download/v1.0.0/openssl.rb`
2 - Run brew with the file downloaded:
`brew install openssl.rb`
